python -u train.py \
  --seq_len 32 \
  --d_model 128 \
  --n_heads 4 \
  --n_layers 2 \
  --batch_size 8 \
  --steps 200 \
  --warmup_steps 10 \
  --eval_every 50 \
  --gen_max_new 20 \
  --n_eval_batches 2 \
