python -u train.py \
  --d_model 128 \
  --n_heads 4 \
  --n_hops 2 \
  --n_attn_modules 2 \
  --n_ff_modules 2 \
  --batch_size 8 \
  --seq_len 64 \
  --steps 200 \
  --eval_every 50 \
  --batch_shards 1 \
  --expert_shards 1 \
