python -u train.py \
  --d_model 128 \
  --n_layers 4 \
  --n_heads 4 \
  --batch_size 8 \
  --seq_len 64 \
  --steps 100 \
  --eval_every 20 \
  --gen_max_new 10 \
  --warmup_steps 10 \
  --wandb_project "dna-mini" \
